settings:
  title: 'Status Page'
  url: 'https://status.blintflix.io' # used for Slack messages
  logo: blintflix_blue.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: blintflix-io # unique identifier
    name: Blintflix
    description: 'Blintflix' # default=empty
    url: 'https://blintflix.io/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: accounts-blintflix-io
    name: accounts.blintflix.io
    description: 'Forgot your password? Or just need an invite?'
    url: 'https://accounts.blintflix.io'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: requests-blintflix-io
    name: requests.blintflix.io
    url: 'https://requests.blintflix.io/'
    method: GET
    expectStatus: 200
    linkable: true
    description: 'I wanna see this movie, can I get it?'
    followRedirect: true

  - id: stats-blintflix-io
    name: stats.blintflix.io
    url: 'https://stats.blintflix.io/'
    method: GET
    expectedStatus: 200
    linkable: true
    description: 'Statistics for the nerds'

  - id: sonarr
    name: Sonarr
    url: 'https://sonarr.blint.me/'
    method: GET
    expectedStatus: 200
    linkable: false
    followRedirect: true
  
  - id: radarr
    name: Radarr
    url: 'https://radarr.blint.me/'
    method: GET
    expectedStatus: 200
    linkable: false
    followRedirect: true

  - id: bazarr
    name: Bazarr
    url: 'https://bazarr.blint.me/'
    method: GET
    expectedStatus: 200
    linkable: false
    followRedirect: true
  
  - id: prowlarr
    name: Prowlarr
    url: 'https://prowlarr.blint.me/'
    method: GET
    expectedStatus: 200
    linkable: false
    followRedirect: true

  - id: lidarr
    name: Lidarr
    url: 'https://lidarr.blint.me/'
    method: GET
    expectedStatus: 200
    linkable: false
    followRedirect: true
  
  - id: readarr
    name: Readarr
    url: 'https://readarr.blint.me/'
    method: GET
    expectedStatus: 200
    linkable: false
    followRedirect: true
  
  - id: q
    name: Q
    url: 'https://q.blint.me/'
    method: GET
    expectedStatus: 200
    linkable: false
    followRedirect: true
    